# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Resume' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Resume
  pod 'MaterialComponents'
  target 'ResumeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
